blank_issues_enabled: false
contact_links:
  - name: Get In Touch
    url: https://discord.gg/feMsefha8D
    about: Join our Discord server to get in touch with the developers and other users of Hero Mancer!
