name: Module Builder

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'TODO.md'
      - '.gitattributes'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.set-release-notes.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Version from Commit Message
        id: get-version
        run: |
          version=$(git log -1 --pretty=%B | grep -o -E '[v]?[0-9]+\.[0-9]+\.[0-9]+' | sed 's/^v//')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Extracted version: $version"

      - name: Set Release Notes from Commit Description
        id: set-release-notes-github
        run: |
          release_notes=$(git log -1 --pretty=%B | grep '^-' | sed 's/^ //')
          echo "release-notes-github<<EOF" >> $GITHUB_ENV
          echo "$release_notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "$release_notes" > release_notes.txt

      - name: Format Release Notes for Discord
        id: format-release-notes-discord
        run: |
          DISCORD_NOTES=$(awk '{printf "%s\\n", $0}' release_notes.txt | sed 's/\\n$//')
          echo "::set-output name=release-notes-discord::$DISCORD_NOTES"

      - name: Update module.json with Version
        run: node .github/workflows/update-module.js ${{ steps.get-version.outputs.version }}

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.release-notes-github }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"dont-forget"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"${REPO_URL}/releases/latest/download/module.json"'",
              "download": "'"${REPO_URL}/releases/download/${{ steps.get-version.outputs.version }}/module.zip"'",
              "notes": "'"${REPO_URL}/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"12.331"'",
                "verified": "'"12.331"'",
                "maximum": "'"12.999"'"
              }
            }
          }'

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          VERSION="${{ steps.get-version.outputs.version }}"
          RELEASE_NOTES="${{ steps.format-release-notes-discord.outputs.release-notes-discord }}"

          # Create JSON payload
          JSON_PAYLOAD=$(jq -n \
            --arg title "Hero Mancer Release: $VERSION" \
            --arg description "$RELEASE_NOTES\n\nCheck it out through the Foundry package manager or the link below:\n<$REPO_URL/releases/tag/$VERSION>" \
            '{embeds: [{title: $title, description: $description}]}')

          # Post to Discord
          curl -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               $DISCORD_WEBHOOK
